sudo: required
services:
  - docker
branches:
  # Restrict push builds to only master
  only:
  - master
before_install:
  # Fail immediately on any error
  - set -e
install:
  # Build containers
  - make nobuild-tests
script:
  - make test-fast
