---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates the MozDef base instance profile and delivery server IAM role"
Resources:
  WebRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  # Attach the instance profile here for cleanlieness.
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        -
          Ref: WebRole
Outputs:
  InstanceProfileArn:
    Description: The arn of the instanceprofile.
    Value: !GetAtt InstanceProfile.Arn
