AWSTemplateFormatVersion: "2010-09-09"
Description: Create MozDef Amazon ES
Parameters:
  SubnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: "Comma-delimited list of subnet IDs within which the ElasticSearch instance will be provisioned."
    Default: "subnet-dd8eacb5,subnet-df8eacb7,subnet-de8eacb6"
  BlockStoreSizeGB:
    Type: Number
    Description: "The size of the Elastic Block Store to have back ElasticSearch, in GigaBytes."
    Default: 100
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: "The VPC ID of the VPC to deploy in"
    Default: "vpc-dc8eacb4"
  MozDefInstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: "The MozDef EC2 Instance security group that accesses ES"
    Default: "sg-8f38dae0"
  ESInstanceCount:
    Type: Number
    Default: 1
    Description: "The number of ElasticSearch nodes in the cluster"
Resources:
## Not currently supported by cloudformation.
#  ESServiceLinkedRole:
#    Type: "AWS::IAM::ServiceLinkedRole"
#    Properties:
#      AWSServiceName: "es.amazonaws.com"
#      Description: "Role to enable Amazon ES to manage your cluster."
  MozDefElasticSearch:
    Type: "AWS::Elasticsearch::Domain"
    Properties:
      VPCOptions:
        SubnetIds:
          - !Select [ 0, !Ref SubnetIds ]
      EBSOptions:
        EBSEnabled: true
        VolumeType: "gp2"
        VolumeSize: !Ref BlockStoreSizeGB
      ElasticsearchVersion: "5.6"
      ElasticsearchClusterConfig:
        InstanceCount: !Ref ESInstanceCount
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:*"
      Tags:
        - Key: "application"
          Value: "mozdef"
        - Key: stack
          Value: !Ref "AWS::StackName"
  MozDefElasticSearchSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "ES Security Group"
      SecurityGroupEgress:
        -
          Description: "Allow all egress traffic"
          IpProtocol: -1
          CidrIp: "0.0.0.0/0"
      SecurityGroupIngress:
        -
          Description: "Allow 443 inbound from the MozDef EC2 SG"
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref MozDefInstanceSecurityGroup
      Tags:
        - Key: "application"
          Value: "mozdef"
        - Key: stack
          Value: !Ref "AWS::StackName"
      VpcId: !Ref VpcId
Outputs:
  ElasticsearchDomainArn:
    Description: "ARN of the provisioned ElasticSearch Cluster"
    Value: !GetAtt MozDefElasticSearch.DomainArn
  ElasticsearchDomainEndpoint:
    Description: "Endpoint of the provisioned ElasticSearch Cluster"
    Value: !GetAtt MozDefElasticSearch.DomainEndpoint
  ElasticsearchKibanaURL:
    Description: "URL for the Kibana UI"
    Value: !Join [ '', [ 'https://', !GetAtt MozDefElasticSearch.DomainEndpoint, "/_plugin/kibana/" ] ]
  ElasticsearchKibanaURLShort:
    Description: "URL for the Kibana UI"
    Value: !Join [ '', [ 'https://', !GetAtt MozDefElasticSearch.DomainEndpoint ] ]
  ElasticsearchURL:
    Description: "URL for the Kibana UI"
    Value: !Join [ '', [ 'http://', !GetAtt MozDefElasticSearch.DomainEndpoint, ":80" ] ]
