AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy MozDef autoscaled EC2 instance group and ALB into AWS
Parameters:
  VpcId:
    Type: "AWS::EC2::VPC::Id"
    Description: "The VPC ID of the VPC to deploy in"
    Default: "vpc-dc8eacb4"
  InstanceType:
    Type: "String"
    Default: "m5.large"
    Description: "EC2 instance type, e.g. m1.small, m1.large, etc."
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: "Name of an existing EC2 KeyPair to enable SSH access to the web server"
    Default: "infosec-pdx-workweek-2018"
  IamInstanceProfile:
    Type: "String"
    Description: "The ARN of the IAM Instance Profile"
    Default: "arn:aws:iam::656532927350:instance-profile/netsecdevbastion-BastionInstanceProfile-12CM3TOELV20R"
  AutoScaleGroupSubnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: "A comma delimited list of subnet IDs"
    Default: "subnet-dd8eacb5,subnet-df8eacb7,subnet-de8eacb6"
  AMIImageId:
    Type: "String"
    Description: "The AMI Image ID to use of the EC2 instance"
    Default: "ami-0e6f50fa0c8c241af"
  MozDefSecurityGroupId:
    Type: "String"
    Description: "The security group to apply to the EC2 instance"
  MozDefLoadBalancerSecurityGroupId:
    Type: "String"
    Description: "The security group to apply to the EC2 instance"
  MozDefACMCertArn:
    Type: "String"
    Description: "The arn of your pre-issued certificate for ssl termination."
    Default: "arn:aws:acm:us-west-2:656532927350:certificate/79f641f2-4046-4754-a28f-4db80d7c0583"
  ESURL:
    Type: "String"
    Description: "The AWS ES endpoint URL"
    Default: http://elasticsearch.example.com/
  KibanaURL:
    Type: "String"
    Description: "The AWS ES Kibana URL"
    Default: https://kibana.example.com/
  AmazonMQHostName:
    Type: "String"
    Description: "The AWS AmazonMQ HostName"
    Default: b-ea1aefe8-b194-4be5-91c3-0e8b2e664151-1.mq.us-west-2.amazonaws.com
  AmazonMQScheme:
    Type: "String"
    Description: "The AWS AmazonMQ Scheme"
    Default: amqp+ssl
  AmazonMQPort:
    Type: "String"
    Description: "The AWS AmazonMQ Port"
    Default: 5671
  AmazonMQUsername:
    Type: "String"
    Description: "The AWS AmazonMQ Username"
    Default: mozdef
  AmazonMQPassword:
    Type: "String"
    NoEcho: true
    Description: "The AWS AmazonMQ User Password"
    Default: example-password
  OIDCClientId:
    Description: "The client ID that your OIDC provider issues you for your Mozdef instance."
    Type: String
    Default: "lGsSlYNdiV6f5tF05pWN3EbQoDPHx44k"
  OIDCClientSecret:
    Type: String
    Description: "The secret that your OIDC provider issues you for your Mozdef instance."
    NoEcho: true
  OIDCDiscoveryURL:
    Type: String
    Default: "https://auth.mozilla.auth0.com/.well-known/openid-configuration"
    Description: "The URL of your OIDC provider's well-known discovery URL"
Resources:
  MozDefElasticLoadBalancingV2TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: "/health"
      Port: 80
      Protocol: HTTP
      Tags:
        - Key: application
          Value: mozdef
        - Key: stack
          Value: !Ref "AWS::StackName"
      VpcId: !Ref VpcId
  MozDefLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      IamInstanceProfile: !Ref IamInstanceProfile
      ImageId: !Ref AMIImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MozDefSecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #cloud-config

          write_files:
          - content: |
              OPTIONS_ESSERVERS=${ESURL}
              OPTIONS_KIBANAURL=${KibanaURL}
              OPTIONS_MQSERVER=${AmazonMQHostName}
              OPTIONS_MQPROTOCOL=${AmazonMQScheme}
              OPTIONS_MQPORT=${AmazonMQPort}
              OPTIONS_MQUSER=${AmazonMQUsername}
              OPTIONS_MQPASSWORD=${AmazonMQPassword}
              # See https://github.com/mozilla-iam/mozilla.oidc.accessproxy/blob/master/README.md#setup
              client_id=${OIDCClientId}
              client_secret=${OIDCClientSecret}
              discovery_url=${OIDCDiscoveryURL}
              backend=http://nginx
              redirect_uri_path=/redirect_uri
              httpsredir=no
            path: /opt/mozdef/docker/compose/cloudy_mozdef.env
          - content: |
              client_id=${OIDCClientId}
              client_secret=${OIDCClientSecret}
              discovery_url=${OIDCDiscoveryURL}
              backend=${KibanaURL}
              redirect_uri_path=/redirect_uri
              httpsredir=no
            path: /opt/mozdef/docker/compose/cloudy_mozdef_kibana.env
          runcmd:
            - chmod 600 /opt/mozdef/docker/compose/cloudy_mozdef.env
            - cd /opt/mozdef && git pull origin infosec_workweek
            - make -C /opt/mozdef -f /opt/mozdef/Makefile  # USE_DKR_IMAGES=docker/compose/docker-compose-norebuild.yml run-cloudy-mozdef
  MozDefAutoScaleGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      DesiredCapacity: 1
      LaunchConfigurationName: !Ref MozDefLaunchConfiguration
      MaxSize: 2
      MinSize: 1
      Tags:
        - Key: Name
          Value: mozdef
          PropagateAtLaunch: true
        - Key: application
          Value: mozdef
          PropagateAtLaunch: true
        - Key: stack
          Value: !Ref "AWS::StackName"
          PropagateAtLaunch: true
      TargetGroupARNs:
        - !Ref MozDefElasticLoadBalancingV2TargetGroup
      TerminationPolicies:
        - OldestLaunchConfiguration
      VPCZoneIdentifier: !Ref AutoScaleGroupSubnetIds
    UpdatePolicy:
     AutoScalingRollingUpdate:
       MinInstancesInService: '1'
       MaxBatchSize: '1'
       PauseTime: PT5S
  MozDefElasticLoadBalancingV2LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      SecurityGroups:
        - !Ref MozDefLoadBalancerSecurityGroupId
      Subnets: !Ref AutoScaleGroupSubnetIds
      Tags:
        - Key: application
          Value: mozdef
        - Key: stack
          Value: !Ref "AWS::StackName"
  MozDefElasticLoadBalancingV2ListenerHttps:
    Type : AWS::ElasticLoadBalancingV2::Listener
    Properties:
      Certificates:
        - CertificateArn: !Ref MozDefACMCertArn
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: MozDefElasticLoadBalancingV2TargetGroup
      LoadBalancerArn:
        Ref: MozDefElasticLoadBalancingV2LoadBalancer
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-2016-08
  MozDefElasticLoadBalancingV2ListenerHttp:
    Type : AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: MozDefElasticLoadBalancingV2TargetGroup
      LoadBalancerArn:
        Ref: MozDefElasticLoadBalancingV2LoadBalancer
      Port: 80
      Protocol: HTTP
