---
AWSTemplateFormatVersion: 2010-09-09
Description: Amazon Elastic File System
Parameters:
  VPCID0:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: Must be the VPC Id of an existing Virtual Private Cloud.
    Default: "vpc-dc8eacb4"
  Subnet:
    Description: Select existing subnets.
    Type: List<AWS::EC2::Subnet::Id>
    Default: "subnet-8931f7ee,subnet-de322aa8,subnet-2582cd7d"
  MozDefSecurityGroup:
    Description: "The security group of the Mozdef endpoint that is accessing EFS"
    Type: AWS::EC2::SecurityGroup::Id
    Default: "sg-02d7fe9627ea068e2"
Resources:
  MountTarget:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId:
        !Ref ElasticFileSystem
      SubnetId:
        !Select [ 0, !Ref 'Subnet' ]
      SecurityGroups:
        [ !Ref MozDefSecurityGroup ]
  ElasticFileSystem:
    Type: AWS::EFS::FileSystem
