---
version: '2.2'
services:
  base:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_base/Dockerfile
  nginx:
    build:
      context: ../../
      dockerfile: docker/compose/nginx/Dockerfile
  kibana:
    build:
      context: ../../
      dockerfile: docker/compose/kibana/Dockerfile
  mongodb:
    build:
      context: ../../
      dockerfile: docker/compose/mongodb/Dockerfile
  elasticsearch:
    build:
      context: ../../
      dockerfile: docker/compose/elasticsearch/Dockerfile
  rabbitmq:
    build:
      context: ../../
      dockerfile: docker/compose/rabbitmq/Dockerfile
  bootstrap:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_bootstrap/Dockerfile
  alertplugins:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_alertplugins/Dockerfile
  alerts:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_alerts/Dockerfile
  cron:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_cron/Dockerfile
  loginput:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_loginput/Dockerfile
  # The generic worker container for all ingest processes
  mq_worker:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_mq_worker/Dockerfile
    restart: "no"
  meteor:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_meteor/Dockerfile
  rest:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_rest/Dockerfile
  syslog:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_syslog/Dockerfile
  tester:
    build:
      context: ../../
      dockerfile: docker/compose/tester/Dockerfile
