---
version: '2.2'
services:
  nginx:
    image: mozdef/mozdef_nginx
    restart: always
    command: /usr/sbin/nginx
    depends_on:
      - meteor
    ports:
      - 80:80
      - 8080:8080
      - 9090:9090
      # - 8081:8081
    networks:
      - default
  mongodb:
    image: mozdef/mozdef_mongodb
    restart: always
    command: /usr/bin/mongod --smallfiles --config /etc/mongod.conf
    volumes:
      - mongodb:/var/lib/mongo
    networks:
      - default
  bootstrap:
    image: mozdef/mozdef_bootstrap
    env_file:
      - cloudy_mozdef.env
    depends_on:
      - base
    networks:
      - default
  # MozDef Specific Containers
  base:
    image: mozdef/mozdef_base
    env_file:
      - cloudy_mozdef.env
    command: bash -c 'su - mozdef -c /opt/mozdef/envs/mozdef/cron/update_geolite_db.sh'
    volumes:
      - geolite_db:/opt/mozdef/envs/mozdef/data
  alertplugins:
    image: mozdef/mozdef_alertplugins
    env_file:
      - cloudy_mozdef.env
    restart: always
    command: bash -c 'source /opt/mozdef/envs/python/bin/activate && python alert_worker.py -c alert_worker.conf'
    depends_on:
      - base
      - alerts
      - bootstrap
    networks:
      - default
  alerts:
    image: mozdef/mozdef_alerts
    env_file:
      - cloudy_mozdef.env
    restart: always
    command: bash -c 'source /opt/mozdef/envs/python/bin/activate && celery -A celeryconfig worker --loglevel=info --beat'
    depends_on:
      - base
      - bootstrap
    networks:
      - default
  cron:
    image: mozdef/mozdef_cron
    env_file:
      - cloudy_mozdef.env
    restart: always
    command: bash -c 'crond -n'
    volumes:
      - cron:/opt/mozdef/envs/mozdef/cron
      - geolite_db:/opt/mozdef/envs/mozdef/data/
    depends_on:
      - base
      - mongodb
    networks:
      - default
  loginput:
    image: mozdef/mozdef_loginput
    env_file:
      - cloudy_mozdef.env
    restart: always
    command: bash -c 'source /opt/mozdef/envs/python/bin/activate && python index.py -c index.conf'
    depends_on:
      - base
      - bootstrap
    networks:
      - default
  meteor:
    image: mozdef/mozdef_meteor
    restart: always
    command: bash -c 'node bundle/main.js'
    depends_on:
      - mongodb
      - rest
      - bootstrap
    networks:
      - default
  rest:
    image: mozdef/mozdef_rest
    env_file:
      - cloudy_mozdef.env
    restart: always
    command: bash -c 'source /opt/mozdef/envs/python/bin/activate && python index.py -c index.conf'
    depends_on:
      - base
      - mongodb
      - bootstrap
    networks:
      - default
  syslog:
    image: mozdef/mozdef_syslog
    env_file:
      - cloudy_mozdef.env
    restart: always
    command: bash -c '/usr/sbin/syslog-ng --no-caps -F'
    depends_on:
      - loginput
    ports:
      - 514:514/udp
      - 514:514
    networks:
      - default
  accessproxy:
    image: mozillaiam/mozilla.oidc.accessproxy
    env_file:
      - cloudy_mozdef.env
    restart: always
    ports:
      - 8888
    networks:
      - default

volumes:
  mongodb:
  cron:
  geolite_db:

networks:
  default:
